### ISSUE TITLE
Snapshot not fully restoring world selection

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/FastAsyncWorldEdit#3107]
### Server Implementation

Paper

### Server Version

1.21.1

### Describe the bug

https://github.com/EngineHub/WorldEdit/issues/2707

```
[21:17:19] [Server thread/INFO]: RedstoneFuture issued server command: //restore
[21:17:19] [AsyncNotifyKeyedQueue - 65/INFO]: WorldEdit: Using com.sk89q.worldedit.world.storage.ZippedMcRegionChunkStore for loading snapshot '/home/redstoneworld/minecraft-server/_backups/hauptserver/2025-02-10-21-13-00.zip'
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 749568 from 4096 using 745472
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 3960832 from 4096 using 3956736
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 2748416 from 4096 using 2744320
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 3715072 from 4096 using 3710976
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 3682304 from 4096 using 3678208
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 172032 from 4096 using 167936
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 81920 from 4096 using 77824
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 2334720 from 4096 using 2330624
[21:17:23] [AsyncNotifyKeyedQueue - 65/ERROR]: Seek to 2752512 from 4096 using 2748416
[...]
```

### To Reproduce

1. Generate a snapshot following this instruction: https://worldedit.enginehub.org/en/latest/usage/snapshots/
2. `//set blue_wool`
3. `//snap list`
4. `//restore`

### Expected behaviour

Actually, all blocks of the selection should be undone correctly.

### Screenshots / Videos

![Image](https://github.com/user-attachments/assets/3c1c350b-41ed-490c-8f07-41b46d823a2f)
_blue = Chunks that have not been undone._

### Fawe Debugpaste

- last test: https://athion.net/ISPaster/paste/view/cc8cd580da5342778c32ea2f495b2f97

### Fawe Version

2.12.3-Paper

### Checklist

- [x] I have included a Fawe debugpaste.
- [x] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

**Comment by RedstoneFuture** [comment]
It works fine locally (Windows), but not on the production server (Linux Debian). I have no idea, why.

Locally, however, I also get these error messages.

![Image](https://github.com/user-attachments/assets/bc15b93a-e1ca-4d33-b0de-cde1b7351579)

```
[00:31:12] [Server thread/INFO]: RedstoneFuture issued server command: //restore
[00:31:12] [AsyncNotifyKeyedQueue - 0/INFO]: WorldEdit: Using com.sk89q.worldedit.world.storage.ZippedMcRegionChunkStore for loading snapshot 'L:\Minecraft\Server\Testserver\PaperMC_1.21.1\plugins\WorldEdit\snapshot\2025-02-11-00-03-00.zip'
[00:31:15] [AsyncNotifyKeyedQueue - 0/ERROR]: Seek to 4014080 from 4096 using 4009984
[00:31:15] [AsyncNotifyKeyedQueue - 0/ERROR]: Seek to 3932160 from 4096 using 3928064
[00:31:16] [AsyncNotifyKeyedQueue - 0/ERROR]: Seek to 475136 from 4096 using 471040
[00:31:16] [AsyncNotifyKeyedQueue - 0/ERROR]: Seek to 3817472 from 4096 using 3813376
```

**Comment by VergilPrime** [comment]
This is fixed in this commit https://github.com/EngineHub/WorldEdit/commit/c20366db5ff0d173bb9bd7ff6bd6f533d427db40

**Comment by RedstoneFuture** [comment]
> This is fixed in this commit [EngineHub/WorldEdit@c20366d](https://github.com/EngineHub/WorldEdit/commit/c20366db5ff0d173bb9bd7ff6bd6f533d427db40)

Thank you. I will test it.

**Comment by VergilPrime** [comment]
Why did you close it? It's fixed in WorldEdit not Fawe :x

**Comment by RedstoneFuture** [comment]
> Why did you close it? It's fixed in WorldEdit not Fawe :x

It should work for FAWE builds with updated WorldEdit dependencies in future versions. It's not a FAWE bug in this case.

**Comment by dordsor21** [comment]
This is awaiting #3137

**Comment by ikuria** [comment]
restore is working, but the errors are still occur...

![Image](https://github.com/user-attachments/assets/e520295f-c5c8-4511-a935-81e5a47c2e41)

**Comment by ikuria** [comment]
still not fixed :(

**Comment by VergilPrime** [comment]
> still not fixed :(

It was definitely working when I tested it, are you sure you have the right build?

**Comment by ikuria** [comment]
I'm sorry, I should have tested the latest version beforehand
